name: Python CI

on:
  push:
    branches: [ "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install httpx pytest-cov python-dotenv

    - name: Lancer les tests
      # C'est ici qu'on donne les clés au robot pour la durée du test
      env:
        DATABASE_URL: postgresql://postgres:sam123@localhost:5432/rh_prediction_db
        SECRET_KEY: "12345"
        API_KEY: "mon_badge_secret_987"
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest