name: Python CI

on:
  push:
    branches: [ "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Installer les outils
      run: |
        python -m pip install --upgrade pip
        # On ajoute python-dotenv qui manquait
        pip install pytest fastapi httpx uvicorn joblib pandas scikit-learn sqlalchemy imblearn xgboost python-dotenv

    - name: Lancer les tests
      run: |
        # PYTHONPATH . permet de dire au robot : "regarde dans le dossier courant pour trouver main.py"
        export PYTHONPATH=$PYTHONPATH:.
        pytest